#!/usr/bin/env bash
#
# Publishes the pacts generated by the consumers (shared folder <root>/pacts)
# to the Pact Broker using the pact-jvm maven plugin (goal publish).
#
# Environment variables (all optional):
#   PACT_BROKER_BASE_URL   default http://localhost:9292
#   PACT_BROKER_USERNAME   default pact
#   PACT_BROKER_PASSWORD   default pact
#   PACT_CONSUMER_VERSION  default 1.0.0   (consumer version in the broker)
#   PACT_CONSUMER_TAG      default main    (tag of the consumer version)
set -euo pipefail

PACT_BROKER_BASE_URL="${PACT_BROKER_BASE_URL:-http://localhost:9292}"
PACT_BROKER_USERNAME="${PACT_BROKER_USERNAME:-pact}"
PACT_BROKER_PASSWORD="${PACT_BROKER_PASSWORD:-pact}"
PACT_CONSUMER_VERSION="${PACT_CONSUMER_VERSION:-1.0.0}"
PACT_CONSUMER_TAG="${PACT_CONSUMER_TAG:-main}"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

if ! ls pacts/*.json >/dev/null 2>&1; then
  echo "ERROR: no pact found in $ROOT_DIR/pacts" >&2
  echo "       Run this first:  make consumer-tests" >&2
  exit 1
fi

echo "Pacts to publish:"
ls -1 pacts/*.json

echo "Publishing to $PACT_BROKER_BASE_URL (version=$PACT_CONSUMER_VERSION, tag=$PACT_CONSUMER_TAG)..."
# -N (non-recursive): the goal must only run on the parent project,
# where the pacts/ folder lives.
mvn -q -N "au.com.dius.pact.provider:maven:4.6.21:publish" \
  -Dpact.pactDirectory=pacts \
  -Dpact.broker.url="$PACT_BROKER_BASE_URL" \
  -Dpact.broker.username="$PACT_BROKER_USERNAME" \
  -Dpact.broker.password="$PACT_BROKER_PASSWORD" \
  -Dpact.projectVersion="$PACT_CONSUMER_VERSION" \
  -Dpact.consumer.tags="$PACT_CONSUMER_TAG"

echo "OK: pacts published to $PACT_BROKER_BASE_URL (tag: $PACT_CONSUMER_TAG)"
